

all:
	mkdir -p ~/.vim/ftdetect
	mkdir -p ~/.vim/ftplugin
	ln -f vim/ftdetect/drcs.vim ~/.vim/ftdetect
	ln -f vim/ftdetect/image.vim ~/.vim/ftdetect
	ln -f vim/ftplugin/drcs.vim ~/.vim/ftplugin
	ln -f vim/ftplugin/image.vim ~/.vim/ftplugin
